### ISSUE TITLE
getData() method always returns null 

### ISSUE THREAD

**Issue by dzarezenko** [mazipan/nuxt-storage#10]
I am trying to implement transactions list storing with:

```
saveTransactionData(txnData) {
    let txnList = getData('txns')
    console.log(txnList)
    if (!txnList) {
      txnList = []
    }
    console.log(txnList)

    txnList.push(txnData)
    setData('txns', txnList, 30, 'd')
  }
```
But `getData('txns')` always returns `null` even if value exists in the Local Storage. So I can't save a list, I always receive only last transaction in storage.

What is wrong?

**Comment by mazipan** [comment]
See sample here: https://codesandbox.io/s/102r751xj
Live view: https://102r751xj.sse.codesandbox.io/

**Comment by dzarezenko** [comment]
@mazipan , your example works fine, but in my nuxt.js project storage is clean any time I reloaded the page, and all local storage connected logic is in this method `saveTransactionData(txnData)`

**Comment by mazipan** [comment]
Maybe because I remove the storage, if detected as expired data 🤔

**Comment by mazipan** [comment]
Can you please update version of `nuxt-storage` to 1.2.1 @dzarezenko?

**Comment by dzarezenko** [comment]
With new version I noticed 2 changes:
1. The Local Storage was not cleaned after page refresh
2. I see `storage is expired` message when receive `null` from storage, but I have the next expiration settings:
```
created: 1557236384640
expiry: 30
unit: "d"
```

**Comment by kevinalexandersurjadi** [comment]
I get the same result, on reload page, I get undefined data of localstorage

**Comment by notjiam** [comment]
@mazipan I think this issue related with my pull request
https://github.com/mazipan/nuxt-storage/pull/76

**Comment by mazipan** [comment]
Will release in 19th August 2019 ya...

**Comment by mazipan** [comment]
Published in 1.2.2

**Comment by mazipan** [comment]
@all-contributors please add @notjiam for tests and bug

**Comment by Quineone** [comment]
This bug still reproduce in `"nuxt-storage": "^1.2.2"`, nuxt version is `"nuxt": "^2.0.0"`
