### ISSUE TITLE
Please how do i clear a particular key from session

### ISSUE THREAD

**Issue by papakay** [mazipan/nuxt-storage#168]
Please I've checked the documentation but didn't see any information on how to clear a particular key from session.

Any information on this please.

**Comment by thetre97** [comment]
@papakay Try `*.removeItem(<key>)`

**Comment by papakay** [comment]
Please can you clarify what `*.` means. The above sample is a bit confusing. Will i need to import `removeItem` just like `clear`, `getData` etc.?

Thank you

**Comment by thetre97** [comment]
That was a wildcard for whatever storage solution you are using - so if you were using local storage:

```js
import nuxtStorage from 'nuxt-storage';

nuxtStorage.localStorage.removeItem('key')
```
You can check the code here: https://github.com/mazipan/nuxt-storage/blob/816935c64b8b2b8a8db7f953489e85ceaadbb23d/src/unified-storage.ts#L123

**Comment by papakay** [comment]
Thank you so much. This is now very clear...
